import React from 'react';
// import { AppContext } from '../../../../context';
import styles from './Articles.css.js';
// import ButtonContainer from '../ButtonContainer';
import ArticleTitle from './ArticleTitle';
import SectionTitle from './SectionTitle.jsx';

const ContentText = ({title, text}) => (
    <div style={styles.contentText}>
        {!!title && <b style={styles.boldText}>{`${title} - `}</b>}{text}
    </div>
);

const SolarArticle = () => {
    // const { trackingState } = useContext(AppContext);

    return(
        <div style={styles.mainConatiner}>
            <div style={styles.contentContainer}>
                <SectionTitle text='Understanding Solar Energy:'/>
            </div>
            <div style={styles.contentContainer}>
                <ArticleTitle text='What is Solar Energy?'/>
                <ContentText text="Solar energy is power obtained by harnessing the energy of the sun's rays. Residential solar energy typically involves installing solar panels on your home's roof or property." />
            </div>
            {/* <ButtonContainer containerId='rampjs_slot2' email={trackingState['email']} title='Search and Compare High Yield Savings'/> */}
            <div style={styles.contentContainer}>
                <ArticleTitle text='Advantages'/>
                <ContentText title='Reduces Electricity Bills:' text="Solar panels generate electricity that can be used in your home, reducing your dependence on the grid." />
                <ContentText title='Environmentally Friendly:' text="Solar energy is a clean, renewable energy source that reduces carbon footprint." />
                <ContentText title='Increases Home Value:' text="Homes with solar energy systems often have a higher market value." />
            </div>
            <div style={styles.contentContainer}>
                <SectionTitle text='How to Obtain Affordable Solar Energy'/>
            </div>
            <div style={styles.contentContainer}>
                <ArticleTitle text='1. Government Incentives and Rebates'/>
                <ContentText title='Federal Solar Tax Credit:' text="In many countries, including the U.S., homeowners can benefit from tax credits when installing solar panels." />
                <ContentText title='State and Local Incentives:' text="Some states and local governments offer additional incentives, rebates, or tax breaks." />
            </div>
            <div style={styles.contentContainer}>
                <ArticleTitle text='2. Solar Leasing or Power Purchase Agreements (PPAs)'/>
                <ContentText title='Lease Panels:' text="You can lease solar panels for a monthly fee, often lower than your typical electricity bill." />
                <ContentText title='PPAs:' text="With a PPA, you agree to purchase the power generated by panels installed on your home at a set rate." />
            </div>
            <div style={styles.contentContainer}>
                <ArticleTitle text='3. Community or Shared Solar'/>
                <ContentText title='Group Projects:' text="If individual solar panels are too expensive, consider joining a community solar project. These allow multiple individuals to benefit from a single, shared solar system." />
            </div>
            <div style={styles.contentContainer}>
                <ArticleTitle text='4. Financing Options'/>
                <ContentText title='Loans:' text="Several financial institutions offer loans specifically for solar panel installations." />
                <ContentText title="Home Equity Loans:" text="You can use home equity loans to finance solar panels, often at lower interest rates." />
            </div>
            <div style={styles.contentContainer}>
                <ArticleTitle text='5. Do It Yourself (DIY) Installations'/>
                <ContentText title='Self-Installation:' text="If you're handy, you can save on installation costs by doing it yourself. However, be aware of the complexity and safety issues involved." />
            </div>
            <div style={styles.contentContainer}>
                <ArticleTitle text='6. Purchase Used or Discounted Panels'/>
                <ContentText title='Second-Hand Panels:' text="Look for used or discounted solar panels. They can be much cheaper, though they may not be as efficient." />
            </div>
            <div style={styles.contentContainer}>
                <ArticleTitle text='7. Energy-Efficient Home Improvements'/>
                <ContentText title='Reduce Energy Consumption:' text="Improving home insulation, using energy-efficient appliances, and LED lighting can reduce your overall energy needs, making a smaller solar system sufficient." />
            </div>
            <div style={styles.contentContainer}>
                <ArticleTitle text='8. Rent-to-Own Programs'/>
                <ContentText title='Flexible Ownership:' text="Some companies offer rent-to-own schemes for solar panels, allowing you to eventually own the system." />
            </div>
            <div style={styles.contentContainer}>
                <ArticleTitle text='9. Scale Accordingly'/>
                <ContentText title='Start Small:' text="Begin with a smaller system to cover part of your energy needs and expand as your budget allows." />
            </div>
            <div style={styles.contentContainer}>
                <ArticleTitle text='Conclusion'/>
                <ContentText text="Adopting solar energy for your home can be a financially sound and environmentally responsible decision. By exploring various options like government incentives, community solar, and DIY installations, you can make the transition to solar more affordable. Remember, while the upfront cost can be significant, the long-term savings and environmental benefits make solar energy a worthwhile investment." />
            </div>
        </div>
    );
};

export default SolarArticle;