const stylesheet = {
    
    // header: {
    //     fontSize: '2.2rem',
    //     padding: '20px 0',
    //     '@media (max-width: 767px)': {
    //         fontSize: '1.45rem',
    //         padding: '10px 10px 0 10px',
    //     },
    // },
    trendingGrid: {
        display: 'flex',
        flexDirection: 'row',
        flexWrap: 'nowrap',
        flexGrow: 1,
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
        '@media (max-width: 767px)': {
            flexDirection: 'column',
        },
    },
    featuredArticleContainer: {
        width: '49%',
        '@media (max-width: 767px)': {
            width: '100%',
            marginBottom: '20px',
        },
    },
    articleCardContainer: {
        width: '49%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        alignItems: 'center',
        '@media (maxWidth: 767px)': {
            width: '100%',
        },
    },
    articleCardContainerRow: {
        width: '100%',
        display: 'flex',
        flexDirection: 'row',
        flexWrap: 'nowrap',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    featuredArticleCard: {
        width: '100%',
        height: '400px',
        backgroundPosition: 'center',
        backgroundSize: 'cover',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderRadius: '10px',
    },
    featuredArticleCardTopRow: {
        width: '100%',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    featuredArticleCardBottomRow: {
        width: '100%',
        backgroundColor: '#0F2789',
        opacity: '0.9',
        borderBottomLeftRadius: '10px',
        borderBottomRightRadius: '10px',
        padding: '10px 20px',
    },
    articleCard: {
        width: '49%',
        height: '190px',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    dateBadgeContainer: {
        marginLeft: '15px',
        marginTop: '15px',
    },
    dateBadge: {
        width: '40px',
        height: '50px',
        backgroundColor: '#2F8DFA',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: '10px',
    },
    dateBadgeDay: {
        fontSize: '1.25rem',
        fontWeight: 'bold',
        color: 'white',
    },
    dateBadgeMonth: {
        fontSize: '0.75rem',
        color: 'white',
    },
    articleCategory: {
        fontSize: '0.75rem',
        color: '#2F8DFA',
        width: '100%',
        textAlign: 'left',
    },
    featuredArticleContent: {
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        margin: '5px 0 10px 0',
    },
    featuredArticleTitle: {
        width: '100%',
        textAlign: 'left',
        fontSize: '1.25rem',
        color: 'white',
        fontWeight: '400',
    },
    featuredArticleDesc: {
        width: '100%',
        textAlign: 'left',
        fontSize: '0.75rem',
        color: 'white',
        marginTop: '5px',
    },
    featuredArticleAuthor: {
        width: '100%',
        textAlign: 'left',
        fontSize: '0.65rem',
        color: 'white',
    },
    articleCardTopRow: {
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        backgroundPosition: 'center',
        backgroundSize: 'cover',
        height: '75%',
        borderRadius: '5px',
    },
    articleCardBottomRow: {
        width: '100%',
        height: '25%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
    },
    articleCardCategory: {
        fontSize: '0.6rem',
        margin: '5px 0',
        color: '#2F8DFA',
        width: '100%',
        textAlign: 'left',
    },
    articleCardTitle: {
        fontSize: '0.8rem',
        color: 'black',
        width: '100%',
        textAlign: 'left',
    },
};
export default stylesheet;