import React from 'react';
import styles from './TermsConditions.css.js';
import UscFullLogo from '../../../assets/Images/usc_full_logo.png';

const domain = 'UnitedStatesCredit.com';

const TermsConditions = () => (
    <div style={styles.container}>
        <div style={styles.logoBar}>
            <img src={UscFullLogo} alt='footer-logo' style={styles.headerLogo}/>
        </div>
        <div style={styles.infoContainer}>

            <h1>{domain} Website Terms of Use</h1>
            <p>
                <b>Terms of Use.</b> The following terms and conditions (“Terms and Conditions”) govern the use of {domain} Web site (the “Site”). The Site is provided by BlueKeel LLC (the "Site Proprietor" or “we”). If you do not agree to these Terms and Conditions, DO NOT access or otherwise use the Site. <b>BY USING THIS SITE, YOU ACCEPT AND AGREE TO ALL TERMS AND CONDITIONS AS APPLIED TO YOUR USE OF THIS SITE.</b> From time to time we may change Terms and Conditions and at any time without notice to you, by posting such changes on the Site. By using the Site you agree to be bound by any such modifications to the Terms and Conditions. You may only use the Site if you are domiciled in the United States and you are 18 years old or older.
            </p>
            <p>
                <b>1. SERVICES AVAILABLE ON THE SITE.</b> The purpose of the Site is to provide consumers with ability to receive comparative offers and quotes from a nationwide network of service providers and brokers, based on the information you have provided. Each Provider may have one or numerous companies with which they will provide you with the most competitive quote. Once you have provided us with the information needed, by sufficiently completing an appropriate online form, we will refer that information to Providers which then may contact you directly. From time to time these Providers may ask for additional information they may need to obtain an accurate quote.We do not provide any of the services covered on this site. In addition, we do not endorse or recommend any companies. We do not guarantee that any of the brokers and/or companies to whom we may forward you and/or your information will contact you or agree to provide you with any service. We are not responsible in any way, for the conduct of the brokers or companies to whom we forward you or your information. If you need personal advice, explanation of coverage, assessment of needs or specific policy or service recommendations, consult with a qualified professional. We reserve all the rights to our Site contents, and may at our discretion change the contents of the Site, or restrict access to certain sections of the Site, or to discontinue any aspect of the Site, including, but not limited to content, features, hours of availability, without notice or penalty.
            </p>
            <p>
                <b>2. THERE IS NO CHARGE TO YOU FOR USE OF THE SITE.</b>
            </p>
            <p>
                <b>3. USER INFORMATION </b>While using the Site, you may be asked to provide, or choose to provide on your own, information (hereinafter “User Information”). The User Information you submit to us in order to products or services and not in any other manner. Our information collection and use policies with respect to the privacy of personal information, with the exception of testimonials, which may be used to advertise our Site, are set forth in our Privacy Policy section, which is incorporated herein by reference for all purposes. Please read our Privacy Policy before submitting your User Information. You acknowledge and agree that you are solely responsible for the accuracy and content of the User Information. We reserve the right to refuse to post or to remove any User Information, in whole or in part, that, in our sole view, are unlawful, unacceptable, undesirable, inappropriate or is in violation of these Terms and Conditions.
            </p>
            <p>
                <b>4. “For Providers” Section. </b>By registering and receiving User Information Provider agreed to adhere to the same Privacy Policy as we do, with regards to the User Information referred to you by us for the expressed purpose of providing product or service quotations. Provider agreed to delete, all user information received, after the contact with the User is established and used for appropriate purpose as set forth in the body of this Agreement, except for information stored in connection with the purchase of a product or service as a result of our referrals.
            </p>
            <p>
                <b>5. Proprietary Rights. </b>Any and all content, code, data or materials of the Site used by you does not grant to you ownership on the Site and is owned by the Site Proprietor BlueKeel LLC, which owns solely and exclusively, including but limited to, all rights, title interest, graphics, data, the look and feel, design and organization of the Site, and the compilation of the content, code, data and materials on the Site, including but not limited to all intellectual property and proprietary rights therein. Your rights are limited to viewing the content on the Site on your internet-compatible device and make single copies or prints of the content on the User Information displayed for your use it for solely for the purpose it was sent to you, and not for other commercial use. To use copy, reproduce, distribute or exploit any content, code, data or materials on the Site otherwise, may be in violation of copyright and other laws of the United States, as well as applicable state laws for such unauthorized use. Our trade name, trademarks, service marks and logo are copyright protected and are not to be used, copied or reproduced by anyone without the expressed and signed written agreement. Any third party's marks, logos etc., which may appear on the Site are the property of their respective owners and can not be used without their written consent.
            </p>
            <p>
                <b>6. </b>User agree that, the User Information referred to you by this Site shall not be used in any way other than intended. Your conduct with regards to persons who's information you received for the above expressed purpose shall not be used in unlawful, threatening, harassing, tortuous, defamatory, vulgar, obscene, libelous, deceptive, fraudulent way. No material should be posted or transmitted to the Site that contain explicit, or graphic depictions of accounts of sexual nature (including language of a violent or threatening nature directed at another individual or group of individuals). Any act toward a any person, who's information was obtained through this Site, including invasive, or hateful, behavior, or conduct, would constitute a criminal offense or give rise to criminal and civil liability. Any transmission to our Site or to a referred by the Site individual's computer, that contain a virus or other harmful component, or false or misleading indications or statements of fact, will serve as cause of actions (including, but not limited to) immediate termination of the Provider relationships.
            </p>
            <p>
                <b>7. </b>You also warrant and agree that you shall not: engage in spamming, flooding, harvesting of e-mail addresses or other personal information, "database spidering," or any other activity with the purpose other than expressed and agree to, or send chain letters. You agree that you will not use the Site in any manner that could damage, disable, overburden, or impair the Site or interfere with any other party's use and enjoyment of the Site.
            </p>
            <p>
                <b>8. </b>You agree to defend, indemnify and hold the Site Proprietor and its directors, officers, employees, agents and affiliates harmless from any and all claims, liabilities, costs and expenses, including reasonable attorneys' fees, arising in any way from your misuse of the Site, your placement or transmission of any message, content, information, software or other materials through the Site, or your breach or violation of the law or of these Terms and Conditions.
            </p>
            <p>
                <b>9. DISCLAIMER OF WARRANTIES.WE HEREBY DISCLAIM ANY WARRANTIES THAT, MAY EXPRESS OR IMPLY THAT THE SITE OR THE SERVICES, OR FUNCTIONS, CONTAINED THEREIN WILL BE TIMELY, SECURE, UNINTERRUPTED OR ERROR FREE. WHILE WE WILL ATTEMPT TO CORRECT ANY ERRORS OR DEFECTS OF .THE SITE IN A TIMELY MANNER, NO GUARANTY OF: NON INTERRUPTION, DELIVERY OF EMAIL, OR ACCESS TO THE SITE AT ALL TIMES, WITHOUT ERRORS.. ALL THE SERVICES ON THIS SITE ARE PROVIDED "AS IS," AND “AS AVAILABLE”, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ACCESS TO DATA, DATA PROCESSING FUNCTIONS, OR ACCURACY, USEFULNESS OF CONTENT, OR LOSS OF INFORMATION. YOU ARE RESPONSIBLE FOR MAINTAINING ALL USER SUBMITTED INFORMATION AND SHOULD RETAIN ALL SUCH DATA AND INFORMATION IN YOUR OWN RECORDS FOR USE IN THE EVENT THAT THE SITE FAILS OR IS ACCESS IS UNAVAILABLE, OR THE DATA OR INFORMATION IS CORRUPTED OR LOST. WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED HEREBY. IF ANY TERM OR STATEMENT FOUND HEREIN MAKE YOU RELUCTANT OR DISSATISFIED WITH THE USE OF THE SITE, WE RECOMMEND TO EXIT AND TO DISCONTINUE USING THE SITE. WE DISCLAIM ANY AND ALL LIABILITY IN THE EVENT THE SITE PROPRIETOR/S OR ANY OF DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, AFFILIATES, OR PROVIDERS OF CONTENT OR A SERVICE ARE VIEWED LIABLE FOR ANY DIRECT, INDIRECT, CONTRIBUTIVE, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM, OR DIRECTLY OR INDIRECTLY RELATED TO USE OF, OR THE INABILITY TO USE THE SITE'S, OR ITS CONTENT, MATERIALS, FUNCTIONS OR APPLICATIONS, INCLUDING, WITHOUT LIMITATION, LOSS OF REVENUE, OR ANTICIPATED OR PERCEIVED PROFITS OR LOST BUSINESS OR LOST SALES.</b>
            </p>
            <p>
                <b>10. </b>User agree that, the User Information referred to you by this Site shall not be used in any way other than intended. Your conduct with regards to persons who's information you received for the above expressed purpose shall not be used in unlawful, threatening, harassing, tortuous, defamatory, vulgar, obscene, libelous, deceptive, fraudulent way. No material should be posted or transmitted to the Site that contain explicit, or graphic depictions of accounts of sexual nature (including language of a violent or threatening nature directed at another individual or group of individuals). Any act toward a any person, who's information was obtained through this Site, including invasive, or hateful, behavior, or conduct, would constitute a criminal offense or give rise to criminal and civil liability. Any transmission to our Site or to a referred by the Site individual's computer, that contain a virus or other harmful component, or false or misleading indications or statements of fact, will serve as cause of actions (including, but not limited to) immediate termination of the Provider relationships.
            </p>
            <p>
                <b>11. Laws </b>The Terms and Conditions and the relationship between you and us shall be governed by the laws of the State of Illinois without regard to any conflict of legal provisions. You agree that any use of action that may arise under the Terms and Conditions shall be commenced and be heard in the appropriate court in the State of Illinois and submit to the personal and exclusive jurisdiction of the courts located within the State of Illinois. Our failure to exercise or enforce any right or provision of the Terms and Conditions shall not constitute a waiver of such right or provision. If any provision of the Terms and Conditions is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to consider the parties' intentions as hereby reflected in the provision the Terms and Conditions, and other unaffected provisions to remain in full force and effect. You agree that regardless of any statute or law to the contrary, any claim or cause of action by you arising out of or related to use of the Site or the Terms and Conditions must be filed by you within one (1) year after such claim or cause of action arose or be barred forever.
            </p>
            <p>
                <b>12. Contact Us </b>If you have any questions about the Agreement, the practices of the Site or your dealings with the Site, please e-mail us at:info@{domain}or send a letter to: BlueKeel LLC, Attn: {domain}, 899 Skokie Blvd, Ste 340, Northbrook, IL 60062
            </p>
        </div>
    </div>
);

export default TermsConditions;